# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 213f5d4c37f83cf5700c449c5c7a158ac5af8b51445d2081931bd884d521b687f85a46a8726e21d11fb2c4e7285feb5b1d4454a0b0dae87e44f4d89e83247d4a

test:
  secret_key_base: 02f3b09316183a6f457c747fb031768f480913543ffe8efb32e4e7cf4eecc2ae754c7fc6b85d0f8d5ebe8800b83f88e318686858330a832b758a6b8610ddf068

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
